package com.excilys.training.selenium;

import static org.junit.Assert.assertEquals;

import java.io.IOException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
//Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.phantomjs.PhantomJSDriver;

import com.excilys.training.dto.CompanyDTO;
import com.excilys.training.dto.ComputerDTO;
import com.excilys.training.service.ComputerService;

import io.github.bonigarcia.wdm.WebDriverManager;

public class addComputerTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	ComputerService computerService = ComputerService.getInstance();
	JavascriptExecutor js;

	@BeforeClass
	static public void setUpClass() throws IOException, SQLException {
		WebDriverManager.chromedriver().setup();

	}
	
	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void addComputer() {
		//expected dto create
		String name = "selenium computer";
		String introducedDate = "2019-05-06";
		String discontinuedDate = "2019-05-07";
		String CompanyDTOname = "Apple Inc.";
		CompanyDTO companyDTO = new CompanyDTO("1",CompanyDTOname);
		ComputerDTO expected = new ComputerDTO(name, introducedDate, discontinuedDate, companyDTO);
		
		driver.get("http://localhost:8080/CDB/");
		driver.manage().window().setSize(new Dimension(1280, 960));
		driver.findElement(By.id("addComputer")).click();
		driver.findElement(By.id("computerName")).click();
		driver.findElement(By.id("computerName")).sendKeys("selenium computer");
		driver.findElement(By.id("introduced")).click();
		driver.findElement(By.id("introduced")).click();
		driver.findElement(By.id("introduced")).sendKeys("06/05/2019");
		driver.findElement(By.id("discontinued")).click();
		driver.findElement(By.id("discontinued")).click();
		driver.findElement(By.id("discontinued")).sendKeys("07/05/2019");
		{
			WebElement dropdown = driver.findElement(By.id("companyId"));
			dropdown.findElement(By.xpath("//option[. = 'Apple Inc.']")).click();
		}
		{
			WebElement element = driver.findElement(By.id("companyId"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).clickAndHold().perform();
		}
		{
			WebElement element = driver.findElement(By.id("companyId"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.id("companyId"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).release().perform();
		}
		driver.findElement(By.id("companyId")).click();
		driver.findElement(By.cssSelector(".btn-primary")).click();
		driver.findElement(By.cssSelector(".navbar-brand")).click();
		List<ComputerDTO> liste = computerService.getAll();
		ComputerDTO actual = liste.get(liste.size()-1);
		assertEquals(expected, actual);
	}
}
