package com.excilys.training.selenium;

import static org.junit.Assert.assertEquals;

import java.io.IOException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.springframework.beans.factory.annotation.Autowired;

import com.excilys.training.service.ComputerService;

import io.github.bonigarcia.wdm.WebDriverManager;

public class SearchTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	
	@Autowired
	private ComputerService computerService;

	@BeforeClass
	static public void setUpClass() throws IOException, SQLException {
		WebDriverManager.chromedriver().setup();

	}
	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void search() {
		final String name = "apple";
		
		// Step # | name | target | value | comment
		// 1 | open | /CDB/dashboard | |
		driver.get("http://localhost:8080/CDB/dashboard");
		// 2 | setWindowSize | 1280x960 | |
		driver.manage().window().setSize(new Dimension(1280, 960));
		// 3 | click | id=searchbox | |
		driver.findElement(By.id("searchbox")).click();
		// 4 | type | id=searchbox | iphone |
		
		driver.findElement(By.id("searchbox")).sendKeys(name);
		// 5 | click | id=searchsubmit | |
		driver.findElement(By.id("searchsubmit")).click();
		long actual = Long.parseLong(driver.findElement(By.id("homeTitle")).getText().replaceFirst(" Computers found", ""));
		long expected = computerService.count(name);
		assertEquals(expected, actual);
		
	}
}